version: "3.9"
services:
  bitcoind-node:
    container_name: bitcoin-node
    image: ruimarinho/bitcoin-core
    restart: always
    expose:
      - "18332"
    ports:
      - "127.0.0.1:18332:18332"  # set up your external node ip
    volumes:
      - ./data/btc/test/coind:/home/bitcoin/.bitcoin
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf