name: test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  test-session-chat:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run test
        run: |
          export PORT=3000
          export APP_ENV=development
          export BITCOIN_RPC_USER=example
          export BITCOIN_RPC_PASSWORD=example
          export BITCOIN_RPC_URL=http://127.0.0.1:18332
          make test